name: '项目集成测试'
on:
  push:
    branches:
      - main
  release:
    types: [ published, created, edited ]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: '配置JDK环境'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      - name: '配置依赖环境'
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - name: '配置编译环境'
        run: |
          chmod +x ./gradlew
          ./gradlew tasks
      - name: '编译项目'
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
      - name: '测试项目'
        run: |
          chmod +x ./gradlew
          ./gradlew clean test
